services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
    ports:
     - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - grafana


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
     - 3023:3000
    restart: unless-stopped
    env_file: .env
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-h44w&2@fhM4Ca!SD}
      # - GF_SERVER_ROOT_URL=https://grafana.example.com/
      # - GF_SERVER_DOMAIN=grafana.example.com
    volumes:
        - grafana-data:/var/lib/grafana
    networks:
      - grafana

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter

    pid: host
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/host'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - grafana

  snmp-exporter:
    image: prom/snmp-exporter
    container_name: snmp-exporter
    ports:
      - 9116:9116
    restart: unless-stopped
    networks:
      - grafana

volumes:
  prom_data:
  grafana-data:

networks:
  grafana:
